### ISSUE TITLE
crypto.createCredentials is deprecated. Use tls.createSecureContext instead.

### ISSUE THREAD

**Issue by mark-bradshaw** [Atlantis-Software/mailx#2]
Whenever I use this module I get this warning in the console:

`(node) crypto.createCredentials is deprecated. Use tls.createSecureContext instead.`

Tracing that deprecation message down I get this:

```
$ node --trace-deprecation index.js 
Trace: crypto.createCredentials is deprecated. Use tls.createSecureContext instead.
    at Object.exports._printDeprecationMessage (internal/util.js:30:13)
    at Object.deprecated [as createCredentials] (internal/util.js:54:22)
    at POP3Client.starttls (/Users/markbradshaw/Documents/projects/node-reporter/node_modules/mailx/lib/poplib.js:179:39)
    at /Users/markbradshaw/Documents/projects/node-reporter/node_modules/mailx/lib/poplib.js:418:10
    at Socket.<anonymous> (/Users/markbradshaw/Documents/projects/node-reporter/node_modules/mailx/lib/poplib.js:139:11)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:529:20)
```

**Comment by mark-bradshaw** [comment]
Might try something like this in `lib/poplib`:

```
var sslcontext;
if (tls.createSecureContext) {
      sslcontext = tls.createSecureContext(options);
} else {
      sslcontext = crypto.createCredentials(options);
}
```

**Comment by atiertant** [comment]
@mark-bradshaw i rewrote this part for node6 support...

**Comment by mark-bradshaw** [comment]
👍
